### ISSUE TITLE
options.imports = false keeps @import in ie.css file

### ISSUE THREAD

**Issue by benabraham** [BlessCSS/grunt-bless#37] opened 2016-03-03 16:05 UTC
I have `imports: false` in Gruntfile.js but there is still `@import` in the resulting file.

**Comment by orangehaze** [comment] 2016-03-03 20:20
I can confirm this is happening to me also.

**Comment by AaronAsAChimp** [comment] 2016-03-07 18:39
I've fixed this issue and it will be in the next release.

**Closed by AaronAsAChimp** 2016-03-07 18:39 UTC
Labels: bug

**Comment by benabraham** [comment] 2016-03-07 22:24
:heart_eyes: Thanks.

**Comment by orangehaze** [comment] 2016-03-07 22:59
@AaronAsAChimp Thanks for the quick fix. 

Is there a way to specify the URL that is used in the import statement? The reason I needed to disable the import in the first place, is that I couldn't get it to correctly reference the split blessed files. For example, it was in "root/stylesheets/filetobeblessed.css", and the import ends up being "import 'stylesheets/filetobeblessed.1.css'", which in the browser translated to "root/**stylesheets/stylesheets** /filetobeblessed.css". This resulted in a 404.

**Comment by AaronAsAChimp** [comment] 2016-03-08 20:42
Yes, the fix for this is coming, I'm waiting for PR #36 and/or PR #38 to be resolved.
