### ISSUE TITLE
Support for specifying file name convention

### ISSUE THREAD

**Issue by dudewad** [BlessCSS/grunt-bless#31] opened 2016-01-11 21:20 UTC
Is there a way to not have files output as "file-whatever-blessed1.css"... etc?
I'd like to specify the suffix. I know could seem trivial but anyone on larger projects might need this feature or see it fit to follow an existing naming convention that this outright breaks.
Also, yes, enterprise clients support a broad employee base and using the word "blessed" in file names could be seen as politically incorrect. That's a serious concern.
Love the plugin, though!!

**Comment by AaronAsAChimp** [comment] 2016-01-22 20:40
This is a duplicate of Issue #12

**Comment by dudewad** [comment] 2016-01-22 20:41
My bad, thanks!

**Closed by AaronAsAChimp** 2016-01-22 20:40 UTC
